#!/bin/sh
#
# little script using whois to determine an array of given domains if it became available and alerts to gotify

echo "{" >> /home/gotify/cli.json
echo "  \"token\": \"${GOTIFY_TOKEN}\"," >> /home/gotify/cli.json
echo "  \"url\": \"${GOTIFY_URL}\"," >> /home/gotify/cli.json
echo "  \"defaultPriority\": 0" >> /home/gotify/cli.json
echo "}" >> /home/gotify/cli.json

# loop through given URLs, check and sent notification using gotify-cli about the state
for domain in $@; do
    state=$(whois $domain | grep Status |  tr -d '\t' | tr ':' '\n' | tail -n +2 | sed "s/^ //")
    if [ "$state" == "NOT AVAILABLE" ]; then
        gotify push -t "DOMAIN-WATCHER" -p 0 "$domain is still not available"
    else
        gotify push -t "DOMAIN-WATCHER" -p 10 "$domain is still not available"
    fi
done
