#!/bin/bash
#
# little script using whois to determine an array of given domains if it became available and alerts to telegram using ntfy

# create telegram configuration based on ENV parameters
mkdir -p /home/watcher/.config/ntfy

echo '[telegram]' > /home/watcher/.config/ntfy/telegram.ini
echo "token = ${TELEGRAM_TOKEN}" >> /home/watcher/.config/ntfy/telegram.ini
echo "chat_id = ${TELEGRAM_CHAT_ID}" >> /home/watcher/.config/ntfy/telegram.ini

# loop through given URLs, check and ntfy using telegram about the state
for domain in $@; do
    state=$(whois $domain | grep Status |  tr -d '\t' | tr ':' '\n' | tail -n +2 | sed "s/^ //")
    if [ "$state" == "NOT AVAILABLE" ]; then
        ntfy -b telegram send "$domain is still not available"
    else
        ntfy -b telegram send "$domain state is $state"
    fi
done
