name: docker-hub-description

on:
  push:
    tags:
      - '*'

jobs:
  update:
    uses: visibilityspots/dockerfile-cloudflared/.github/workflows/docker-hub-description.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
