name: CI

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t visibilityspots/domain-watcher:dev .

      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.1.0
        with:
          version: 'v0.3.20'

      - name: Execute Goss tests
        run: time dgoss run visibilityspots/domain-watcher:dev domain.org || ((i++))

  buildx:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            visibilityspots/domain-watcher:latest
            visibilityspots/domain-watcher:${{ github.ref_name }}

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true

