name: CI

on:
  push:
    tags:
      - '*'
jobs:
  main:
    uses: visibilityspots/dockerfile-cloudflared/.github/workflows/main.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GOSS_CMD: ${{ secrets.GOSS_CMD }}
